# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Aserto.Topaz
PackageVersion: 0.32.50
PackageLocale: en-US
Publisher: Aserto
PublisherUrl: https://aserto.com/
PublisherSupportUrl: https://github.com/aserto-dev/topaz/issues
Author: Gert Drapers
PackageName: Topaz
PackageUrl: https://github.com/aserto-dev/topaz
License: Apache-2.0
LicenseUrl: https://github.com/aserto-dev/topaz/blob/HEAD/LICENSE
ShortDescription: ReBAC & ABAC Application Authorization Solution
Tags:
- abac
- access-control
- api
- authorization
- cloud-native
- golang
- opa
- rbac
- rebac
- security
- zanzibar
ReleaseNotes: |-
  Changelog
  - e9ced22 AuthZEN Access service (#540)
  - dfbebf4 Move controller to topaz (#535)
  - f44a43c Update OpenAPI handler (#539)
  - 73131ce update go-topaz-ui:0.1.18 (#536)
  - df38608 update go-topaz-ui:0.1.19 (#538)
ReleaseNotesUrl: https://github.com/aserto-dev/topaz/releases/tag/v0.32.50
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/aserto-dev/topaz/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
